### ISSUE TITLE
Could not Upload File

### ISSUE THREAD

**Issue by Codzaa** [qmmughal/ckeditor5-blazor#2]
![q1](https://user-images.githubusercontent.com/35093657/136639983-65abe61d-8136-4dbf-b7c2-af582604768c.JPG)

After running your example locally on my machine without making an changes I receive the following error. Are there any further steps I was supposed to take to make it work successfully? 

Thank you! @qmmughal

**Comment by qmmughal** [comment]
@Codzaa you need to put a proper url which accept file 

UrlToPostImage = "your own url"
